sonar.projectKey=houssem670_Ai_Incident
sonar.organization=houssem-fkih

sonar.sources=backend/app,frontend/src,nuclei-api
sonar.tests=backend/tests

sonar.python.version=3.12
sonar.python.coverage.reportPaths=backend/coverage.xml

sonar.exclusions=**/node_modules/**,**/.venv/**,**/dist/**,**/__pycache__/**