{{- if .Values.resourceQuota.enabled }}

apiVersion: v1
kind: ResourceQuota

metadata:
  name: {{ .Values.resourceQuota.name }}
  namespace: {{ .Values.namespace.name }}

spec:
  hard:

    requests.cpu: {{ .Values.resourceQuota.requests.cpu }}
    requests.memory: {{ .Values.resourceQuota.requests.memory }}

    limits.cpu: {{ .Values.resourceQuota.limits.cpu }}
    limits.memory: {{ .Values.resourceQuota.limits.memory }}

    pods: "{{ .Values.resourceQuota.pods }}"

    services: "{{ .Values.resourceQuota.services }}"

    persistentvolumeclaims: "{{ .Values.resourceQuota.persistentVolumeClaims }}"

    configmaps: "{{ .Values.resourceQuota.configMaps }}"

    secrets: "{{ .Values.resourceQuota.secrets }}"

{{- end }}