{{- if .Values.secret.enabled }}

apiVersion: v1
kind: Secret

metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace.name }}

type: Opaque

stringData:
  POSTGRES_USER: {{ .Values.secret.postgresUser | quote }}

  POSTGRES_PASSWORD: {{ .Values.secret.postgresPassword | quote }}

  POSTGRES_DB: {{ .Values.secret.postgresDatabase | quote }}

  SECRET_KEY: {{ .Values.secret.jwtSecret | default (randAlphaNum 64) | quote }}
  
  INTERNAL_API_KEY: {{ .Values.secret.internalApiKey | default (randAlphaNum 40) | quote }}
{{- end }}