name: AI Incident - CI/CD

on:
  push:
    branches:
      - "**"

  pull_request:
    branches:
      - main

  workflow_dispatch:

env:
  APP_NAME: ai-incident
  BACKEND_IMAGE: ${{ secrets.DOCKER_USERNAME }}/ai-incident-backend
  FRONTEND_IMAGE: ${{ secrets.DOCKER_USERNAME }}/ai-incident-frontend
  IMAGE_TAG: ${{ github.sha }}

permissions:
  contents: read

# ============================================================
# 1. TEST
# ============================================================

jobs:

  backend_tests:
    name: Backend Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}

        ports:
          - 5432:5432

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install backend dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest httpx pytest-cov

      - name: Run backend tests
        working-directory: backend
        env:
          # --- Application ---
          APP_NAME: "SOC Platform API"
          API_VERSION: v1

          # --- Server ---
          HOST: 0.0.0.0
          PORT: "8000"

          # --- PostgreSQL (service container ci-dessus) ---
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}

          # --- Auth / JWT ---
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          ALGORITHM: HS256
          ACCESS_TOKEN_EXPIRE_MINUTES: "60"

          # --- CORS ---
          CORS_ALLOWED_ORIGINS: http://localhost:8080

          # --- Internal API ---
          INTERNAL_API_KEY: ${{ secrets.INTERNAL_API_KEY }}

        run: |
          pytest -v --cov=app --cov-report=xml:coverage.xml
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: backend/coverage.xml
          retention-days: 1


  frontend_tests:
    name: Frontend Build
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Build frontend
        working-directory: frontend
        run: npm run build


# ============================================================
# 2. SONARQUBE
# ============================================================
  sonarqube:
    name: SonarQube Cloud
    runs-on: ubuntu-latest

    needs:
      - backend_tests
      - frontend_tests

    steps:

      # ============================================================
      # Checkout repository
      # ============================================================

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # ============================================================
      # Download Python coverage report
      # ============================================================

      - name: Download coverage report
        uses: actions/download-artifact@v4
        with:
          name: coverage-report
          path: backend/

      # ============================================================
      # Verify Sonar configuration
      # ============================================================

      - name: Verify Sonar configuration
        run: |
          echo "===== sonar-project.properties ====="
          cat sonar-project.properties

          echo "===== coverage.xml ====="
          ls -lh backend/coverage.xml

      # ============================================================
      # SonarQube Cloud Scan
      # ============================================================

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}



# ============================================================
  ##3. SNYK
# ============================================================

  snyk_scan:
    name: Snyk Security Scan
    runs-on: ubuntu-latest
    needs:
      - backend_tests
      - frontend_tests

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install backend dependencies
      working-directory: backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Snyk Backend Scan
      working-directory: backend
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      run: |
        npm install -g snyk
        snyk auth $SNYK_TOKEN
        snyk test --file=requirements.txt \
          --package-manager=pip \
          --severity-threshold=high \
          || true

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "22"
        cache: npm
        cache-dependency-path: frontend/package-lock.json

    - name: Install frontend dependencies
      working-directory: frontend
      run: npm ci

    - name: Snyk Frontend Scan
      working-directory: frontend
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      run: |
        npx snyk test \
          --severity-threshold=high \
          || true

# ============================================================
# 4. DOCKER BUILD
# ============================================================

  docker_build:
    name: Build Docker Images
    runs-on: ubuntu-latest

    needs:
      - sonarqube
      - snyk_scan

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Backend
        run: |
          docker build \
            -t ${{ env.BACKEND_IMAGE }}:${{ env.IMAGE_TAG }} \
            ./backend

      - name: Build Frontend
        run: |
          docker build \
            -t ${{ env.FRONTEND_IMAGE }}:${{ env.IMAGE_TAG }} \
            ./frontend

      - name: Save Backend Image
        run: |
          mkdir -p images

          docker save \
            -o images/backend.tar \
            ${{ env.BACKEND_IMAGE }}:${{ env.IMAGE_TAG }}

      - name: Save Frontend Image
        run: |
          docker save \
            -o images/frontend.tar \
            ${{ env.FRONTEND_IMAGE }}:${{ env.IMAGE_TAG }}

      - name: Upload Docker Images
        uses: actions/upload-artifact@v4
        with:
          name: docker-images
          path: images/
          retention-days: 1



# ============================================================
# 5. TRIVY
# ============================================================

  trivy_scan:
    name: Trivy Image Scan
    runs-on: ubuntu-latest
    needs: docker_build

    steps:

    - name: Download Docker images
      uses: actions/download-artifact@v4
      with:
        name: docker-images
        path: images/

    - name: Load Backend image
      run: |
        docker load -i images/backend.tar

    - name: Load Frontend image
      run: |
        docker load -i images/frontend.tar

    - name: Run Trivy Backend Scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: '${{ env.BACKEND_IMAGE }}:${{ env.IMAGE_TAG }}'
        format: table
        severity: HIGH,CRITICAL
        exit-code: '0'
        ignore-unfixed: true

    - name: Run Trivy Frontend Scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: '${{ env.FRONTEND_IMAGE }}:${{ env.IMAGE_TAG }}'
        format: table
        severity: HIGH,CRITICAL
        exit-code: '0'
        ignore-unfixed: true


  container_test:
    name: Container Test
    runs-on: ubuntu-latest

    needs:
      - docker_build
      - trivy_scan

    steps:

      # ============================================================
      # Checkout
      # ============================================================

      - name: Checkout
        uses: actions/checkout@v4

      # ============================================================
      # Download Docker images
      # ============================================================

      - name: Download Docker images
        uses: actions/download-artifact@v4
        with:
          name: docker-images
          path: images/

      # ============================================================
      # Load Docker images into Docker
      # ============================================================

      - name: Load Docker images
        run: |
          docker load -i images/backend.tar
          docker load -i images/frontend.tar

      # ============================================================
      # Docker Network
      # ============================================================

      - name: Create Docker network
        run: |
          docker network create soc-network

      # ============================================================
      # PostgreSQL  
      # ============================================================

      - name: Start PostgreSQL
        run: |
          docker run -d \
            --name postgres-test \
            --network soc-network \
            -e POSTGRES_USER="${{ secrets.POSTGRES_USER }}" \
            -e POSTGRES_PASSWORD="${{ secrets.POSTGRES_PASSWORD }}" \
            -e POSTGRES_DB="${{ secrets.POSTGRES_DB }}" \
            postgres:15

      - name: Wait for PostgreSQL
        run: |
          echo "Waiting for PostgreSQL..."

          for i in {1..30}; do
            if docker exec postgres-test pg_isready \
              -U "${{ secrets.POSTGRES_USER }}" \
              -d "${{ secrets.POSTGRES_DB }}"; then

              echo "PostgreSQL is ready!"
              exit 0
            fi

            echo "PostgreSQL is not ready yet..."
            sleep 2
          done

          echo "PostgreSQL failed to become ready."

          docker logs postgres-test

          exit 1

      # ============================================================
      # Backend
      # ============================================================

      - name: Start Backend
        run: |
          docker run -d \
            --name backend-test \
            --network soc-network \
            -p 8000:8000 \
            -e APP_NAME="SOC Platform API" \
            -e API_VERSION="v1" \
            -e HOST="0.0.0.0" \
            -e PORT="8000" \
            -e POSTGRES_HOST="postgres-test" \
            -e POSTGRES_PORT="5432" \
            -e POSTGRES_USER="${{ secrets.POSTGRES_USER }}" \
            -e POSTGRES_PASSWORD="${{ secrets.POSTGRES_PASSWORD }}" \
            -e POSTGRES_DB="${{ secrets.POSTGRES_DB }}" \
            -e SECRET_KEY="${{ secrets.SECRET_KEY }}" \
            -e ALGORITHM="HS256" \
            -e ACCESS_TOKEN_EXPIRE_MINUTES="60" \
            -e CORS_ALLOWED_ORIGINS="http://localhost:5173" \
            -e INTERNAL_API_KEY="${{ secrets.INTERNAL_API_KEY }}" \
            "${{ env.BACKEND_IMAGE }}:${{ env.IMAGE_TAG }}"

      # ============================================================
      # Check Backend Container
      # ============================================================

      - name: Check Backend Container
        run: |
          echo "===== Docker containers ====="
          docker ps -a

          echo "===== Backend status ====="
          docker inspect backend-test \
            --format='Status={{.State.Status}} ExitCode={{.State.ExitCode}} Running={{.State.Running}}'

          echo "===== Backend logs ====="
          docker logs backend-test || true

      # ============================================================
      # Wait for Backend
      # ============================================================

      - name: Wait for Backend
        run: |
          echo "Waiting for Backend..."

          for i in {1..30}; do

            if curl -fsS http://127.0.0.1:8000/ > /dev/null; then
              echo "Backend is ready!"
              exit 0
            fi

            echo "Backend is not ready yet..."
            sleep 2
          done

          echo "Backend failed to become ready."

          echo "===== Docker containers ====="
          docker ps -a

          echo "===== Backend logs ====="
          docker logs backend-test

          exit 1

      # ============================================================
      # Test Backend
      # ============================================================

      - name: Test Backend
        run: |
          curl --fail --show-error --verbose \
            http://127.0.0.1:8000/

      # ============================================================
      # Frontend
      # ============================================================

      - name: Start Frontend
        run: |
          docker run -d \
            --name frontend-test \
            --network soc-network \
            -p 8080:80 \
            "${{ env.FRONTEND_IMAGE }}:${{ env.IMAGE_TAG }}"

      # ============================================================
      # Check Frontend Container
      # ============================================================

      - name: Check Frontend Container
        run: |
          echo "===== Docker containers ====="
          docker ps -a

          echo "===== Frontend status ====="
          docker inspect frontend-test \
            --format='Status={{.State.Status}} ExitCode={{.State.ExitCode}} Running={{.State.Running}}'

          echo "===== Frontend logs ====="
          docker logs frontend-test || true

      # ============================================================
      # Wait for Frontend
      # ============================================================

      - name: Wait for Frontend
        run: |
          echo "Waiting for Frontend..."

          for i in {1..30}; do

            if curl -fsS http://127.0.0.1:8080/ > /dev/null; then
              echo "Frontend is ready!"
              exit 0
            fi

            echo "Frontend is not ready yet..."
            sleep 2
          done

          echo "Frontend failed to become ready."

          echo "===== Docker containers ====="
          docker ps -a

          echo "===== Frontend logs ====="
          docker logs frontend-test

          exit 1

      # ============================================================
      # Test Frontend
      # ============================================================

      - name: Test Frontend
        run: |
          curl --fail --show-error --verbose \
            http://127.0.0.1:8080/

      # ============================================================
      # Logs - Always
      # ============================================================

      - name: Show Backend Logs
        if: always()
        run: |
          docker logs backend-test || true

      - name: Show Frontend Logs
        if: always()
        run: |
          docker logs frontend-test || true

      - name: Show PostgreSQL Logs
        if: always()
        run: |
          docker logs postgres-test || true


# ============================================================
# 7. DOCKER HUB
# ============================================================

  docker_push:
    name: Push Images to DockerHub
    runs-on: ubuntu-latest

    needs: container_test

    permissions:
      contents: read

    steps:

      - name: Download Docker images
        uses: actions/download-artifact@v4
        with:
          name: docker-images
          path: images/

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Load images
        run: |
          docker load -i images/backend.tar
          docker load -i images/frontend.tar

      - name: Push Backend
        run: |
          docker push \
            ${{ env.BACKEND_IMAGE }}:${{ env.IMAGE_TAG }}

      - name: Push Frontend
        run: |
          docker push \
            ${{ env.FRONTEND_IMAGE }}:${{ env.IMAGE_TAG }}

  deploy_aks:
    name: Deploy to Azure AKS
    runs-on: ubuntu-latest

    needs:
      - docker_push

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
           creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS Context
        uses: azure/aks-set-context@v4
        with:
           resource-group: ai-incident-rg
           cluster-name: ai-incident-aks

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Deploy Application
        run: |
          kubectl delete namespace ai-incident --ignore-not-found=true
          kubectl wait --for=delete namespace/ai-incident --timeout=180s || true

          kubectl create namespace ai-incident

          helm upgrade --install ai-incident ./helm \
          --namespace ai-incident \
          -f helm/values.yaml \
          -f helm/values-azure.yaml \
          --set secret.postgresUser=${{ secrets.POSTGRES_USER }} \
          --set secret.postgresPassword=${{ secrets.POSTGRES_PASSWORD }} \
          --set backend.image.repository=${{ env.BACKEND_IMAGE }} \
          --set backend.image.tag=${{ github.sha }} \
          --set frontend.image.repository=${{ env.FRONTEND_IMAGE }} \
          --set frontend.image.tag=${{ github.sha }}

      - name: Wait for Backend
        run: |
           kubectl rollout status deployment/backend -n ai-incident

      - name: Wait for Frontend
        run: |
           kubectl rollout status deployment/frontend -n ai-incident

      - name: Show Kubernetes Resources
        run: |
          kubectl get all -n ai-incident
          kubectl get ingress -n ai-incident

  monitoring:
    name: Install Prometheus & Grafana
    runs-on: ubuntu-latest

    needs:
      - deploy_aks

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set AKS Context
      uses: azure/aks-set-context@v4
      with:
        resource-group: ai-incident-rg
        cluster-name: ai-incident-aks

    - name: Install Helm
      uses: azure/setup-helm@v4

    - name: Add Prometheus Helm Repository
      run: |
        helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
        helm repo update

    - name: Install kube-prometheus-stack
      run: |
        helm upgrade --install monitoring prometheus-community/kube-prometheus-stack \
        --namespace monitoring \
        --create-namespace \
        -f helm/monitoring/prometheus-values.yaml \
        -f helm/monitoring/grafana-values.yaml \
        --set grafana.adminPassword=${{ secrets.GRAFANA_ADMIN_PASSWORD }}

    - name: Apply ServiceMonitors
      run: |
        kubectl apply -f helm/monitoring/servicemonitor-backend.yaml --validate=false || true
        kubectl apply -f helm/monitoring/servicemonitor-postgres.yaml --validate=false || true

    - name: Wait for Monitoring
      run: |
        kubectl rollout status deployment/monitoring-grafana -n monitoring --timeout=10m || true

    - name: Show Monitoring Resources
      run: |
        kubectl get pods -n monitoring
        kubectl get svc -n monitoring
  
       
